.TH GRUB-GET-KERNEL-SETTINGS 3 "Thu Jun 25 2015"
.SH NAME
\fBgrub-get-kernel-settings\fR \(em Evaluate the system's kernel installation settings for use while making a grub configuration file.

.SH SYNOPSIS
\fBgrub-get-kernel-settings\fR [OPTION]

.SH DESCRIPTION
\fBgrub-get-kernel-settings\fR reads the kernel installation settings on the host system, and emits a set of grub settings suitable for use when creating a grub configuration file.

.SH OPTIONS
.TP
-h, --help
Display program usage and exit.
.TP
-v, --version
Display the current version.

.SH SEE ALSO
.BR "info grub"
